### ISSUE TITLE
difference of this package

### ISSUE THREAD

**Issue by VictorPadovan1997** [jefflinwood/cordova-plugin-twiliovoicesdk#102]
What is the difference of this package:

https://github.com/jefflinwood/twilio_client_phonegap

For:

https://github.com/jefflinwood/cordova-plugin-twiliovoicesdk/

**Comment by jefflinwood** [comment]
The Twilio Client plugin is for an outdated, deprecated version of the Twilio Voice Client for iOS and Android.

This plugin is the current version. Thanks!
