### ISSUE TITLE
Echo During Call

### ISSUE THREAD

**Issue by PaulPaulDevelops** [jefflinwood/cordova-plugin-twiliovoicesdk#36]
Hey All,

I wanted to post and ask if anybody has experienced any echo during a call. If so, how did you resolve this? Is this plugin utilizing any of Twilios echo cancellation software? I have also submitted a ticket to Twilio asking about the echo cancellation software as well.

I'm utilizing this plugin for an Ionic 1 (specifically version 1.3.1) project to connect to Twilio to make phone calls. The plugin works great! Able to connect and everything is running smoothly on iOS and Android. 

I have noticed during testing that this happens more on Android devices. Not sure if this is related.

If you need me to provide any more information please let me know. Thank you! :)

**Comment by jefflinwood** [comment]
Hi,

I haven't heard any echos, but that doesn't mean that they wouldn't be there in your scenario. All of that would most likely be coming from the individual voice SDKs - the Phonegap plugin shouldn't be introducing any latency into the actual audio communications.

It could be something to be addressed in the Android Voice SDK, especially if you can make a scenario that reproduces it (for instance, over LTE or when you call a Skype number, or whatever else makes it happen).

Thanks for using the plugin!
