### ISSUE TITLE
Cordova version 

### ISSUE THREAD

**Issue by tonysumi** [jefflinwood/cordova-plugin-twiliovoicesdk#38]
The following errors have occurred:
• In Android on 11-01-2018 at 19:04:31 - Error installing Cordova plugin: https://github.com/jefflinwood/twilio-voice-phonegap-plugin.git. Your plugin does not support this Cordova version.

trying to run your plugin in Cordova 8.0.0 , cordova android 7.0.0

**Comment by tonysumi** [comment]
@jefflinwood , Please suggest!!!
 This Plugin was working fine last year (2017).  
But now I can't use twilio-voice-phonegap-plugin in my project. 
Can you please check at your end ?

Thanks in advance

**Comment by tonysumi** [comment]
The problem was with plugin.xml       line 39 <dependency id="phonegap-plugin-push"/>

**Comment by jefflinwood** [comment]
With the push plugin?

        <dependency id="phonegap-plugin-push"/>
