### ISSUE TITLE
After updating IOS to 11.4 version, it does not work

### ISSUE THREAD

**Issue by raviverma89** [jefflinwood/cordova-plugin-twiliovoicesdk#49]
It was working good untill i updated my IOS,
i checked error on Xcode console, it gives below error
....SIP registration failed, status=403 (Forbidden)

**Comment by BorntraegerMarc** [comment]
The plugin works perfectly for me on iOS 11.4 and 12

**Comment by raviverma89** [comment]
@BorntraegerMarc , Did you update your twilio library in xcode manually?

**Comment by BorntraegerMarc** [comment]
No...

**Comment by BorntraegerMarc** [comment]
This issue should be closed...
