### ISSUE TITLE
Install guide is lacking.

### ISSUE THREAD

**Issue by nurfgun** [jefflinwood/cordova-plugin-twiliovoicesdk#64]
When I tried installing this plugin, All I got was
```
You need to download __Twilio Voice SDK for iOS__ from https://media.twiliocdn.com/sdk/ios/voice/releases/3.1.0/twilio-voice-ios-3.1.0.tar.bz2. Uncompress the download - you will need to follow two steps that plugman can not do yet:

* Add the Twilio Voice framework (TwilioVoice.framework) to your Xcode project
* Add the Twilio Voice framework (TwilioVoice.framework) as an embedded binary to your Xcode project
```

Most of people use Cordova project because either they don't AND don't want to know  a thing about native languages or even though they know some but don't want to bother with them.

just "ADD" to Xcode project was not so much helpful to me, cause I am the former.

spent hours looking into native developments  to understand the concept of framework and how to add or embed....

closely I read a few threads on how to do it in the Cordova way
https://stackoverflow.com/questions/36650522/custom-cordova-plugin-add-framework-to-embedded-binaries

or documents on the native way of opening up the xcode and doing all the steps.

none worked for me.

The example project seems dead and does not contain any infomation on that either.

I'm out of hints. please kindly point me to the right direction.

Thanks.

**Comment by jefflinwood** [comment]
Hi,

Unfortunately, those two steps need to be done in Xcode. Cordova is missing
the necessary tooling in the iOS plugin to automatically add these as part
of the installation process.

Try dragging the framework into the Xcode project, and then on the Xcode
project General Settings screen, click the plus button under Embedded
Binaries and choose the TwilioVoice framework.

Thanks,
Jeff

**Comment by nurfgun** [comment]
Thanks for quick reply.

This is what I did :

1. dragged and dropped the framework file into the left column of Xcode project.
2. Dialog showed up with "Copy items if needed" checked, "create folder references" checked, and target being "GoogleToolboxForMac".
3. clicked "Finish" button.
4. went to General settings tab, scrolled down to the Embedded Binaries, and clicked the plus button.
5. could not find the framework from the list shown so I clicked the Add Other...button and add framework file.
6. Dialog similar to the former dialog showed up again with "Copy items if needed" checked, "create groups".
7 Clicked the Finish button.
8 clicked the play button in the left side of the top button bar.
9 the build failed with "Module 'TwilioVoice' not found"

help!

**Comment by jefflinwood** [comment]
Try making sure that the target is whatever your app’s name is -
GoogleToolboxForMac isn’t your app’s main target.

**Comment by nurfgun** [comment]
Finally got it to work.
this is what i did differently from before
1. drag and drop the framework into the Frameworks folder of my porject
2. add the framework from the saved(?) folder at Embedded Binaries in General settings tabs
Happy weekend 👍

**Comment by Finesse** [comment]
I tried the steps described above and got the following error:

```
Multiple commands produce '~/Library/Developer/Xcode/DerivedData/MyProject-gfdzvobiitcprxhdmxyddxndhwys/Build/Products/Debug-iphonesimulator/MyProject.app/Frameworks/TwilioVoice.framework':
1) Target 'MyProject' has copy command from '~/Documents/Coding/Ajaxy/MyProjectMobile/platforms/ios/TwilioVoice.framework' to '~/Library/Developer/Xcode/DerivedData/MyProject-gfdzvobiitcprxhdmxyddxndhwys/Build/Products/Debug-iphonesimulator/MyProject.app/Frameworks/TwilioVoice.framework'
2) That command depends on command in Target 'MyProject': script phase “[CP] Embed Pods Frameworks”
```

Still can't solve it. An installation instruction is still required.
