### ISSUE TITLE
The difference between js sdk and this repository

### ISSUE THREAD

**Issue by mozhn** [jefflinwood/cordova-plugin-twiliovoicesdk#81]
Hello, first of thanks for the plugin. I have a question. I used javascript sdk in my application. Is what I do right? Should I use this plugin?

**Comment by schmorrison** [comment]
This plugin is to be used in Cordova apps (eg. Ionic) on mobile devices. If you want to use Twilio on the computer browser you must use the JS SDK.

This plugin loads the Android/iOS SDK and exposes a set of methods for using the native SDK in JavaScript.
