### ISSUE TITLE
Incoming calls IOS 

### ISSUE THREAD

**Issue by krolow** [jefflinwood/cordova-plugin-twiliovoicesdk#82]
I'm trying to use it in iOS 

I do see that the token get registered I get this log:

" Registered Voice Client for VOIP Push""

But when I call the identity nothing happens... any idea in how to debug it?

**Comment by schmorrison** [comment]
I believe you must have Firebase Cloud Messaging setup and enabled to receive incoming calls. FCM token must be added as a push credential in Twilio control panel. AFAIR

**Comment by krolow** [comment]
hmm okay

I have follow these steps: https://www.twilio.com/docs/voice/voip-sdk/ios/get-started#bullet7

- Create VoIP Service Certificate
-  Create a Push Credential with your VoIP Service Certificate

But I still not receiving the incoming calls

**Comment by krolow** [comment]
it's fixed the issue was related to not enable the voip certificate as sandbox
