### ISSUE TITLE
Upgrade to Twilio Voice SDK 6.x

### ISSUE THREAD

**Issue by djanowski** [jefflinwood/cordova-plugin-twiliovoicesdk#84]
https://www.twilio.com/docs/voice/voip-sdk/ios/changelog#621

**Comment by jefflinwood** [comment]
Thanks! This is definitely on the list of improvements to make

**Comment by jefflinwood** [comment]
Fixed in https://github.com/jefflinwood/cordova-plugin-twiliovoicesdk/pull/88
